### ISSUE TITLE
Unable to compile.  Can't find size_t

### ISSUE THREAD

**Issue by cholcombe973** [zargony/rust-fuse#81]
This is likely a goof on my end but I'm having trouble getting rust-fuse to compile.  It's failing at ffi-sys:
```
   Compiling libffi-sys v0.4.6
error: failed to run custom build command for `libffi-sys v0.4.6`
process didn't exit successfully: `/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-40d92df5f46790ce/build-script-build` (exit code: 101)
--- stdout
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
continue configure in default builddir "./x86_64-unknown-linux-gnu"
....exec /bin/bash .././configure "--srcdir=.." "--enable-builddir=x86_64-unknown-linux-gnu" "linux
gnu"
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gsed... sed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... no
checking for c++... c++
checking whether we are using the GNU C++ compiler... yes
checking whether c++ accepts -g... yes
checking dependency style of c++... gcc3
checking dependency style of gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... c++ -E
checking for ld used by c++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the c++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for c++ option to produce PIC... -fPIC -DPIC
checking if c++ PIC flag -fPIC -DPIC works... yes
checking if c++ static flag -static works... yes
checking if c++ supports -c -o file.o... yes
checking if c++ supports -c -o file.o... (cached) yes
checking whether the c++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking size of size_t... 8
checking for C compiler vendor... gnu
checking whether C compiler accepts -fstrict-aliasing... yes
checking whether C compiler accepts -ffast-math... yes
checking for gcc architecture flag... 
checking for x86 cpuid 0 output... d:68747541:444d4163:69746e65
checking for x86 cpuid 1 output... 600f20:6080800:3e98320b:178bfbff
checking whether C compiler accepts -march=amdfam10... yes
checking for gcc architecture flag... -march=amdfam10
checking whether C compiler accepts -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10... yes
checking CFLAGS for maximum warnings... -Wall
checking whether to enable maintainer-specific portions of Makefiles... no
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking for mmap... yes
checking for mkostemp... yes
checking for sys/mman.h... (cached) yes
checking for mmap... (cached) yes
checking whether read-only mmap of a plain file works... yes
checking whether mmap from /dev/zero works... yes
checking for MAP_ANON(YMOUS)... yes
checking whether mmap with MAP_ANON(YMOUS) works... yes
checking for ANSI C header files... (cached) yes
checking for memcpy... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking size of double... 8
checking size of long double... 16
checking whether byte ordering is bigendian... no
checking assembler .cfi pseudo-op support... yes
checking assembler supports pc related relocs... yes
checking assembler .ascii pseudo-op support... yes
checking assembler .string pseudo-op support... yes
checking for _ prefix in compiled symbols... no
checking toolchain supports unwind section type... yes
checking whether .eh_frame section should be read-only... yes
checking for __attribute__((visibility("hidden")))... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating include/Makefile
config.status: creating include/ffi.h
config.status: creating Makefile
config.status: creating testsuite/Makefile
config.status: creating man/Makefile
config.status: creating libffi.pc
config.status: creating fficonfig.h
config.status: fficonfig.h is unchanged
config.status: linking ../src/x86/ffitarget.h to include/ffitarget.h
config.status: executing buildir commands
config.status: create top_srcdir/Makefile guessed from local Makefile
config.status: build in x86_64-unknown-linux-gnu (HOST=x86_64-unknown-linux-gnu)
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing include commands
config.status: executing src commands
MAKE x86_64-unknown-linux-gnu : 1 * install
make[1]: Entering directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu'
Making install in include
make[2]: Entering directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/include'
make[3]: Entering directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/include'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/libffi-3.2.1/include'
 /usr/bin/install -c -m 644 ffi.h ffitarget.h '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/libffi-3.2.1/include'
make[3]: Leaving directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/include'
make[2]: Leaving directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/include'
Making install in testsuite
make[2]: Entering directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/testsuite'
make[3]: Entering directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/testsuite'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/testsuite'
make[2]: Leaving directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/testsuite'
Making install in man
make[2]: Entering directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/man'
make[3]: Entering directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/man'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/share/man/man3'
 /usr/bin/install -c -m 644 ../../man/ffi.3 ../../man/ffi_call.3 ../../man/ffi_prep_cif.3 ../../man/ffi_prep_cif_var.3 '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/share/man/man3'
make[3]: Leaving directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/man'
make[2]: Leaving directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu/man'
make[2]: Entering directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu'
depbase=`echo src/prep_cif.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10  -Wall -fexceptions -MT src/prep_cif.lo -MD -MP -MF $depbase.Tpo -c -o src/prep_cif.lo ../src/prep_cif.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/prep_cif.lo -MD -MP -MF src/.deps/prep_cif.Tpo -c ../src/prep_cif.c  -fPIC -DPIC -o src/.libs/prep_cif.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/prep_cif.lo -MD -MP -MF src/.deps/prep_cif.Tpo -c ../src/prep_cif.c -o src/prep_cif.o >/dev/null 2>&1
depbase=`echo src/types.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10  -Wall -fexceptions -MT src/types.lo -MD -MP -MF $depbase.Tpo -c -o src/types.lo ../src/types.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/types.lo -MD -MP -MF src/.deps/types.Tpo -c ../src/types.c  -fPIC -DPIC -o src/.libs/types.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/types.lo -MD -MP -MF src/.deps/types.Tpo -c ../src/types.c -o src/types.o >/dev/null 2>&1
depbase=`echo src/raw_api.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10  -Wall -fexceptions -MT src/raw_api.lo -MD -MP -MF $depbase.Tpo -c -o src/raw_api.lo ../src/raw_api.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/raw_api.lo -MD -MP -MF src/.deps/raw_api.Tpo -c ../src/raw_api.c  -fPIC -DPIC -o src/.libs/raw_api.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/raw_api.lo -MD -MP -MF src/.deps/raw_api.Tpo -c ../src/raw_api.c -o src/raw_api.o >/dev/null 2>&1
depbase=`echo src/java_raw_api.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10  -Wall -fexceptions -MT src/java_raw_api.lo -MD -MP -MF $depbase.Tpo -c -o src/java_raw_api.lo ../src/java_raw_api.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/java_raw_api.lo -MD -MP -MF src/.deps/java_raw_api.Tpo -c ../src/java_raw_api.c  -fPIC -DPIC -o src/.libs/java_raw_api.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/java_raw_api.lo -MD -MP -MF src/.deps/java_raw_api.Tpo -c ../src/java_raw_api.c -o src/java_raw_api.o >/dev/null 2>&1
depbase=`echo src/closures.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10  -Wall -fexceptions -MT src/closures.lo -MD -MP -MF $depbase.Tpo -c -o src/closures.lo ../src/closures.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/closures.lo -MD -MP -MF src/.deps/closures.Tpo -c ../src/closures.c  -fPIC -DPIC -o src/.libs/closures.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/closures.lo -MD -MP -MF src/.deps/closures.Tpo -c ../src/closures.c -o src/closures.o >/dev/null 2>&1
depbase=`echo src/x86/ffi64.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10  -Wall -fexceptions -MT src/x86/ffi64.lo -MD -MP -MF $depbase.Tpo -c -o src/x86/ffi64.lo ../src/x86/ffi64.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/x86/ffi64.lo -MD -MP -MF src/x86/.deps/ffi64.Tpo -c ../src/x86/ffi64.c  -fPIC -DPIC -o src/x86/.libs/ffi64.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10 -Wall -fexceptions -MT src/x86/ffi64.lo -MD -MP -MF src/x86/.deps/ffi64.Tpo -c ../src/x86/ffi64.c -o src/x86/ffi64.o >/dev/null 2>&1
depbase=`echo src/x86/unix64.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool    --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src  -I. -I../include -Iinclude -I../src  -MT src/x86/unix64.lo -MD -MP -MF $depbase.Tpo -c -o src/x86/unix64.lo ../src/x86/unix64.S &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -I. -I../include -Iinclude -I../src -MT src/x86/unix64.lo -MD -MP -MF src/x86/.deps/unix64.Tpo -c ../src/x86/unix64.S  -fPIC -DPIC -o src/x86/.libs/unix64.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -I. -I../include -Iinclude -I../src -MT src/x86/unix64.lo -MD -MP -MF src/x86/.deps/unix64.Tpo -c ../src/x86/unix64.S -o src/x86/unix64.o >/dev/null 2>&1
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10  -Wall -fexceptions   -o libffi_convenience.la  src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo                                src/x86/ffi64.lo src/x86/unix64.lo src/x86/ffi.lo src/x86/sysv.lo          
libtool: link: rm -fr  .libs/libffi_convenience.a .libs/libffi_convenience.la
libtool: link: ar cru .libs/libffi_convenience.a src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffi.o src/x86/.libs/sysv.o 
libtool: link: ranlib .libs/libffi_convenience.a
libtool: link: ( cd ".libs" && rm -f "libffi_convenience.la" && ln -s "../libffi_convenience.la" "libffi_convenience.la" )
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=amdfam10  -Wall -fexceptions -no-undefined -version-info `grep -v '^#' ../libtool-version`    -o libffi.la -rpath /home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo                                src/x86/ffi64.lo src/x86/unix64.lo src/x86/ffi.lo src/x86/sysv.lo          
libtool: link: rm -fr  .libs/libffi.a .libs/libffi.la .libs/libffi.lai .libs/libffi.so .libs/libffi.so.6 .libs/libffi.so.6.0.4
libtool: link: gcc -shared  -fPIC -DPIC  src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffi.o src/x86/.libs/sysv.o    -O3 -march=amdfam10   -Wl,-soname -Wl,libffi.so.6 -o .libs/libffi.so.6.0.4
libtool: link: (cd ".libs" && rm -f "libffi.so.6" && ln -s "libffi.so.6.0.4" "libffi.so.6")
libtool: link: (cd ".libs" && rm -f "libffi.so" && ln -s "libffi.so.6.0.4" "libffi.so")
libtool: link: ar cru .libs/libffi.a  src/prep_cif.o src/types.o src/raw_api.o src/java_raw_api.o src/closures.o src/x86/ffi64.o src/x86/unix64.o src/x86/ffi.o src/x86/sysv.o
libtool: link: ranlib .libs/libffi.a
libtool: link: ( cd ".libs" && rm -f "libffi.la" && ln -s "../libffi.la" "libffi.la" )
make[3]: Entering directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu'
 /bin/mkdir -p '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libffi.la '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib'
libtool: install: /usr/bin/install -c .libs/libffi.so.6.0.4 /home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib/libffi.so.6.0.4
libtool: install: (cd /home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib && { ln -s -f libffi.so.6.0.4 libffi.so.6 || { rm -f libffi.so.6 && ln -s libffi.so.6.0.4 libffi.so.6; }; })
libtool: install: (cd /home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib && { ln -s -f libffi.so.6.0.4 libffi.so || { rm -f libffi.so && ln -s libffi.so.6.0.4 libffi.so; }; })
libtool: install: /usr/bin/install -c .libs/libffi.lai /home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib/libffi.la
libtool: install: /usr/bin/install -c .libs/libffi.a /home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib/libffi.a
libtool: install: chmod 644 /home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib/libffi.a
libtool: install: ranlib /home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib/libffi.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/chris/.rvm/bin:/home/chris/.rvm/bin:/home/chris/.multirust/toolchains/beta/cargo/bin:/home/chris/.multirust/toolchains/stable/bin:/sbin" ldconfig -n /home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib
----------------------------------------------------------------------
Libraries have been installed in:
   /home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/../lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/share/info'
 /usr/bin/install -c -m 644 ../doc/libffi.info '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/share/info'
 install-info --info-dir='/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/share/info' '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/share/info/libffi.info'
 /bin/mkdir -p '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/pkgconfig'
 /usr/bin/install -c -m 644 libffi.pc '/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/pkgconfig'
make[3]: Leaving directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu'
make[2]: Leaving directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu'
make[1]: Leaving directory '/home/chris/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.4.6/libffi/x86_64-unknown-linux-gnu'

--- stderr
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:31: installing './compile'
configure.ac:19: installing './missing'
Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
configure: WARNING: unrecognized options: --disable-docs
configure: WARNING: unrecognized options: --disable-docs
configure: WARNING: unrecognized options: --disable-docs
../src/closures.c: In function ‘dlmmap_locked’:
../src/closures.c:488:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^
../src/closures.c:500:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/libffi-3.2.1/include/ffi.h:114:3: error: unknown type name 'size_t'
/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/libffi-3.2.1/include/ffi.h:292:1: error: unknown type name 'size_t'
/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/libffi-3.2.1/include/ffi.h:305:1: error: unknown type name 'size_t'
/home/chris/repos/glusterfs-fuse/target/debug/build/libffi-sys-c180ae0cc8ed998b/out/libffi-root/lib/libffi-3.2.1/include/ffi.h:333:26: error: unknown type name 'size_t'
thread 'main' panicked at '
        **********
        Bindgen generation failed. Please file a bug report.
        **********
    : ()', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This works fine on a fresh ubuntu 16.04 laptop so it's probably something silly that I misconfigured.  Any help is greatly appreciated!

**Comment by cholcombe973** [comment]
Just as a test I made a little hello-world.c and made a variable with type size_t.  It compiled fine with gcc.

**Comment by cholcombe973** [comment]
I fixed my issue.  I deleted a bunch of 14.04 libraries and it magically started working.
